# Generated by Django 3.2.6 on 2021-08-20 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contas',
        ),
    ]
